version: '3'
services:
  postgresdb:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env 
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
  # key-cloak:
  #   image: "quay.io/keycloak/keycloak:12.0.1"
  #   env_file:
  #     - key-cloak.env 
  #   ports:
  #     - 8081:8080
volumes:
  database-data:
  
  
