package dede.srm.models;
// Generated Jun 14, 2021, 4:25:43 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AreaType generated by hbm2java
 */
@Entity
@Table(name = "area_type", schema = "public")
public class AreaType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8237535319497369940L;
	private Long id;
	private String name;
	private Date createDate;
	private Date updateDate;
	private String remark;
	private Long createBy;
	private Long updateBy;
	private Set<AreaT> areaTs = new HashSet<AreaT>(0);

	public AreaType() {
	}

	public AreaType(Long id, String name, Date createDate, Date updateDate) {
		this.id = id;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public AreaType(Long id, String name, Date createDate, Date updateDate, String remark, Long createBy, Long updateBy,
			Set<AreaT> areaTs) {
		this.id = id;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.remark = remark;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.areaTs = areaTs;
	}

	@Id
	@SequenceGenerator(name = "area_type_id_seq", sequenceName = "area_type_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "area_type_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by")
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaType")
	public Set<AreaT> getAreaTs() {
		return this.areaTs;
	}

	public void setAreaTs(Set<AreaT> areaTs) {
		this.areaTs = areaTs;
	}

}
