package dede.srm.models;
// Generated Jun 14, 2021, 4:25:43 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AreaT generated by hbm2java
 */
@Entity
@Table(name = "area_t", schema = "public")
public class AreaT implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4328232283368434911L;
	private Long id;
	private AreaType areaType;
	private Building building;
	private String name;
	private String areaDetail;
	private Date createDate;
	private Date updateDate;
	private String remark;
	private String adminName;
	private String adminDetail;
	private Long createBy;
	private Long updateBy;
	private Short floorNumber;
	private Set<Storage> storages = new HashSet<Storage>(0);
	private Set<Device> devices = new HashSet<Device>(0);

	public AreaT() {
	}

	public AreaT(Long id, AreaType areaType, Building building, String name, Date createDate, Date updateDate) {
		this.id = id;
		this.areaType = areaType;
		this.building = building;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public AreaT(Long id, AreaType areaType, Building building, String name, String areaDetail, Date createDate,
			Date updateDate, String remark, String adminName, String adminDetail, Long createBy, Long updateBy,
			Short floorNumber, Set<Storage> storages, Set<Device> devices) {
		this.id = id;
		this.areaType = areaType;
		this.building = building;
		this.name = name;
		this.areaDetail = areaDetail;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.remark = remark;
		this.adminName = adminName;
		this.adminDetail = adminDetail;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.floorNumber = floorNumber;
		this.storages = storages;
		this.devices = devices;
	}

	@Id
	@SequenceGenerator(name = "area_t_id_seq", sequenceName = "area_t_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "area_t_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_type_id", nullable = false)
	public AreaType getAreaType() {
		return this.areaType;
	}

	public void setAreaType(AreaType areaType) {
		this.areaType = areaType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building_id", nullable = false)
	public Building getBuilding() {
		return this.building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "area_detail")
	public String getAreaDetail() {
		return this.areaDetail;
	}

	public void setAreaDetail(String areaDetail) {
		this.areaDetail = areaDetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "admin_name")
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "admin_detail")
	public String getAdminDetail() {
		return this.adminDetail;
	}

	public void setAdminDetail(String adminDetail) {
		this.adminDetail = adminDetail;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by")
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "floor_number")
	public Short getFloorNumber() {
		return this.floorNumber;
	}

	public void setFloorNumber(Short floorNumber) {
		this.floorNumber = floorNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaT")
	public Set<Storage> getStorages() {
		return this.storages;
	}

	public void setStorages(Set<Storage> storages) {
		this.storages = storages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaT")
	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

}
