package dede.srm.models;
// Generated Feb 17, 2021, 3:01:45 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommonValue generated by hbm2java
 */
@Entity
@Table(name = "common_value", schema = "public")
public class CommonValue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 540996257494036648L;
	private Long id;
	private String key;
	private String value;
	private Date createBy;
	private Date updateBy;
	private String remark;

	public CommonValue() {
	}

	public CommonValue(Long id, String key, Date createBy, Date updateBy) {
		this.id = id;
		this.key = key;
		this.createBy = createBy;
		this.updateBy = updateBy;
	}

	public CommonValue(Long id, String key, String value, Date createBy, Date updateBy, String remark) {
		this.id = id;
		this.key = key;
		this.value = value;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "key", nullable = false, length = 100)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_by", nullable = false, length = 29)
	public Date getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Date createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_by", nullable = false, length = 29)
	public Date getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Date updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
