package dede.srm.models;
// Generated Feb 17, 2021, 3:01:45 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompntCpu generated by hbm2java
 */
@Entity
@Table(name = "compnt_cpu", schema = "public")
public class CompntCpu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6183537376167509208L;
	private Long id;
	private ProductBrand productBrand;
	private String clockBase;
	private String architecture;
	private Integer core;
	private Integer thread;
	private Date createDate;
	private Date updateDate;
	private Long createBy;
	private Long updateBy;
	private String remark;

	public CompntCpu() {
	}

	public CompntCpu(Long id, Date createDate, Date updateDate, Long createBy, Long updateBy) {
		this.id = id;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
	}

	public CompntCpu(Long id, ProductBrand productBrand, String clockBase, String architecture, Integer core,
			Integer thread, Date createDate, Date updateDate, Long createBy, Long updateBy, String remark) {
		this.id = id;
		this.productBrand = productBrand;
		this.clockBase = clockBase;
		this.architecture = architecture;
		this.core = core;
		this.thread = thread;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pd_brand_id")
	public ProductBrand getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(ProductBrand productBrand) {
		this.productBrand = productBrand;
	}

	@Column(name = "clock_base")
	public String getClockBase() {
		return this.clockBase;
	}

	public void setClockBase(String clockBase) {
		this.clockBase = clockBase;
	}

	@Column(name = "architecture")
	public String getArchitecture() {
		return this.architecture;
	}

	public void setArchitecture(String architecture) {
		this.architecture = architecture;
	}

	@Column(name = "core")
	public Integer getCore() {
		return this.core;
	}

	public void setCore(Integer core) {
		this.core = core;
	}

	@Column(name = "thread")
	public Integer getThread() {
		return this.thread;
	}

	public void setThread(Integer thread) {
		this.thread = thread;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 22)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "create_by", nullable = false)
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by", nullable = false)
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
