package dede.srm.models;
// Generated Feb 17, 2021, 3:01:45 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompntRam generated by hbm2java
 */
@Entity
@Table(name = "compnt_ram", schema = "public")
public class CompntRam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4067908355442624304L;
	private Long id;
	private ProductBrand productBrand;
	private BigDecimal memSize;
	private String memType;
	private BigDecimal bus;
	private Date createDate;
	private Date updateDate;
	private String createBy;
	private String updateBy;
	private String remark;

	public CompntRam() {
	}

	public CompntRam(Long id, Date createDate, Date updateDate, String createBy, String updateBy) {
		this.id = id;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
	}

	public CompntRam(Long id, ProductBrand productBrand, BigDecimal memSize, String memType, BigDecimal bus,
			Date createDate, Date updateDate, String createBy, String updateBy, String remark) {
		this.id = id;
		this.productBrand = productBrand;
		this.memSize = memSize;
		this.memType = memType;
		this.bus = bus;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pd_brand_id")
	public ProductBrand getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(ProductBrand productBrand) {
		this.productBrand = productBrand;
	}

	@Column(name = "mem_size", precision = 131089, scale = 0)
	public BigDecimal getMemSize() {
		return this.memSize;
	}

	public void setMemSize(BigDecimal memSize) {
		this.memSize = memSize;
	}

	@Column(name = "mem_type")
	public String getMemType() {
		return this.memType;
	}

	public void setMemType(String memType) {
		this.memType = memType;
	}

	@Column(name = "bus", precision = 131089, scale = 0)
	public BigDecimal getBus() {
		return this.bus;
	}

	public void setBus(BigDecimal bus) {
		this.bus = bus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 22)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "create_by", nullable = false)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by", nullable = false)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
