package dede.srm.models;
// Generated Feb 17, 2021, 3:01:45 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Component generated by hbm2java
 */
@Entity
@Table(name = "component", schema = "public")
public class Component implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2449176290633636974L;
	private Long id;
	private Device device;
	private String name;
	private String compntRef;
	private String compntRefId;
	private String amount;
	private Date createDate;
	private Date updateDate;
	private String createBy;
	private String updateBy;
	private String admin;
	private String adminDetail;
	private String equipmentNumber;
	private String remark;

	public Component() {
	}

	public Component(Long id, Device device, String compntRef, String compntRefId, Date createDate, Date updateDate,
			String createBy, String updateBy) {
		this.id = id;
		this.device = device;
		this.compntRef = compntRef;
		this.compntRefId = compntRefId;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
	}

	public Component(Long id, Device device, String name, String compntRef, String compntRefId, String amount,
			Date createDate, Date updateDate, String createBy, String updateBy, String admin, String adminDetail,
			String equipmentNumber, String remark) {
		this.id = id;
		this.device = device;
		this.name = name;
		this.compntRef = compntRef;
		this.compntRefId = compntRefId;
		this.amount = amount;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.admin = admin;
		this.adminDetail = adminDetail;
		this.equipmentNumber = equipmentNumber;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "compnt_ref", nullable = false, length = 3)
	public String getCompntRef() {
		return this.compntRef;
	}

	public void setCompntRef(String compntRef) {
		this.compntRef = compntRef;
	}

	@Column(name = "compnt_ref_id", nullable = false)
	public String getCompntRefId() {
		return this.compntRefId;
	}

	public void setCompntRefId(String compntRefId) {
		this.compntRefId = compntRefId;
	}

	@Column(name = "amount")
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 22)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "create_by", nullable = false)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by", nullable = false)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "admin")
	public String getAdmin() {
		return this.admin;
	}

	public void setAdmin(String admin) {
		this.admin = admin;
	}

	@Column(name = "admin_detail")
	public String getAdminDetail() {
		return this.adminDetail;
	}

	public void setAdminDetail(String adminDetail) {
		this.adminDetail = adminDetail;
	}

	@Column(name = "equipment_number")
	public String getEquipmentNumber() {
		return this.equipmentNumber;
	}

	public void setEquipmentNumber(String equipmentNumber) {
		this.equipmentNumber = equipmentNumber;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
