package dede.srm.models;
// Generated Jun 14, 2021, 4:37:18 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "device", schema = "public")
public class Device implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6622973634380290937L;
	private Long id;
	private AreaT areaT;
	private DeviceType deviceType;
	private Storage storage;
	private String equipmentNumber;
	private String name;
	private Date createDate;
	private Date updateDate;
	private String remark;
	private String adminName;
	private String adminDetail;
	private Long createBy;
	private Long updateBy;
	private String username;
	private String password;
	private Long pdBrandId;
	private Set<System> systems = new HashSet<System>(0);

	public Device() {
	}

	public Device(Long id, AreaT areaT, DeviceType deviceType, String name, Date createDate, Date updateDate) {
		this.id = id;
		this.areaT = areaT;
		this.deviceType = deviceType;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Device(Long id, AreaT areaT, DeviceType deviceType, Storage storage, String equipmentNumber, String name,
			Date createDate, Date updateDate, String remark, String adminName, String adminDetail, Long createBy,
			Long updateBy, String username, String password, Long pdBrandId, Set<System> systems) {
		this.id = id;
		this.areaT = areaT;
		this.deviceType = deviceType;
		this.storage = storage;
		this.equipmentNumber = equipmentNumber;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.remark = remark;
		this.adminName = adminName;
		this.adminDetail = adminDetail;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.username = username;
		this.password = password;
		this.pdBrandId = pdBrandId;
		this.systems = systems;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public AreaT getAreaT() {
		return this.areaT;
	}

	public void setAreaT(AreaT areaT) {
		this.areaT = areaT;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_type_id", nullable = false)
	public DeviceType getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(DeviceType deviceType) {
		this.deviceType = deviceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_id")
	public Storage getStorage() {
		return this.storage;
	}

	public void setStorage(Storage storage) {
		this.storage = storage;
	}

	@Column(name = "equipment_number", length = 40)
	public String getEquipmentNumber() {
		return this.equipmentNumber;
	}

	public void setEquipmentNumber(String equipmentNumber) {
		this.equipmentNumber = equipmentNumber;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "admin_name")
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "admin_detail")
	public String getAdminDetail() {
		return this.adminDetail;
	}

	public void setAdminDetail(String adminDetail) {
		this.adminDetail = adminDetail;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by")
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "pd_brand_id")
	public Long getPdBrandId() {
		return this.pdBrandId;
	}

	public void setPdBrandId(Long pdBrandId) {
		this.pdBrandId = pdBrandId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "device")
	public Set<System> getSystems() {
		return this.systems;
	}

	public void setSystems(Set<System> systems) {
		this.systems = systems;
	}

}
