package dede.srm.models;
// Generated Apr 16, 2021, 4:17:54 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IpAddress generated by hbm2java
 */
@Entity
@Table(name = "ip_address", schema = "public")
public class IpAddress implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 519158399775211922L;
	private Long id;
	private String ipAddress;
	private String ipVersion;
	private Long refId;
	private String refName;
	private String description;
	private Date createDate;
	private Date updateDate;
	private String remark;
	private String domainName;

	public IpAddress() {
	}

	public IpAddress(Long id, String ipAddress, String ipVersion, Long refId, String refName, Date createDate,
			Date updateDate) {
		this.id = id;
		this.ipAddress = ipAddress;
		this.ipVersion = ipVersion;
		this.refId = refId;
		this.refName = refName;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public IpAddress(Long id, String ipAddress, String ipVersion, Long refId, String refName, String description,
			Date createDate, Date updateDate, String remark, String domainName) {
		this.id = id;
		this.ipAddress = ipAddress;
		this.ipVersion = ipVersion;
		this.refId = refId;
		this.refName = refName;
		this.description = description;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.remark = remark;
		this.domainName = domainName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ip_address", nullable = false, length = 40)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "ip_version", nullable = false, length = 20)
	public String getIpVersion() {
		return this.ipVersion;
	}

	public void setIpVersion(String ipVersion) {
		this.ipVersion = ipVersion;
	}

	@Column(name = "ref_id", nullable = false)
	public Long getRefId() {
		return this.refId;
	}

	public void setRefId(Long refId) {
		this.refId = refId;
	}

	@Column(name = "ref_name", nullable = false, length = 50)
	public String getRefName() {
		return this.refName;
	}

	public void setRefName(String refName) {
		this.refName = refName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 22)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "domain_name", length = 50)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

}
