package dede.srm.models;
// Generated Jan 21, 2021, 4:18:59 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", schema = "public")
public class Log implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7824787536242471173L;
	private Long id;
	private User user;
	private String logType;
	private String decription;
	private String remark;
	private String relatedTable;
	private String relatedTableId;
	private Date createDate;

	public Log() {
	}

	public Log(Long id, User user, String logType, String decription, Date createDate) {
		this.id = id;
		this.user = user;
		this.logType = logType;
		this.decription = decription;
		this.createDate = createDate;
	}

	public Log(Long id, User user, String logType, String decription, String remark, String relatedTable,
			String relatedTableId, Date createDate) {
		this.id = id;
		this.user = user;
		this.logType = logType;
		this.decription = decription;
		this.remark = remark;
		this.relatedTable = relatedTable;
		this.relatedTableId = relatedTableId;
		this.createDate = createDate;
	}

	@Id
	@SequenceGenerator(name = "log_id_seq", sequenceName = "log_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "log_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "log_type", nullable = false, length = 3)
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	@Column(name = "decription", nullable = false)
	public String getDecription() {
		return this.decription;
	}

	public void setDecription(String decription) {
		this.decription = decription;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "related_table", length = 50)
	public String getRelatedTable() {
		return this.relatedTable;
	}

	public void setRelatedTable(String relatedTable) {
		this.relatedTable = relatedTable;
	}

	@Column(name = "related_table_id")
	public String getRelatedTableId() {
		return this.relatedTableId;
	}

	public void setRelatedTableId(String relatedTableId) {
		this.relatedTableId = relatedTableId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
