package dede.srm.models;
// Generated Feb 17, 2021, 3:01:45 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Storage generated by hbm2java
 */
@Entity
@Table(name = "storage", schema = "public")
public class Storage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4950841897127066077L;
	private Long id;
	private ProductBrand productBrand;
	private AreaT room;
	private StorageType storageType;
	private String equipmentNumber;
	private String name;
	private Date createDate;
	private Date updateDate;
	private String remark;
	private String adminName;
	private String adminDetail;
	private Long createBy;
	private Long updateBy;
	private Set<Device> devices = new HashSet<Device>(0);

	public Storage() {
	}

	public Storage(Long id, StorageType storageType, Date createDate, Date updateDate) {
		this.id = id;
		this.storageType = storageType;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Storage(Long id, ProductBrand productBrand, AreaT room, StorageType storageType, String equipmentNumber,
			String name, Date createDate, Date updateDate, String remark, String adminName, String adminDetail,
			Long createBy, Long updateBy, Set<Device> devices) {
		this.id = id;
		this.productBrand = productBrand;
		this.room = room;
		this.storageType = storageType;
		this.equipmentNumber = equipmentNumber;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.remark = remark;
		this.adminName = adminName;
		this.adminDetail = adminDetail;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.devices = devices;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pd_brand_id")
	public ProductBrand getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(ProductBrand productBrand) {
		this.productBrand = productBrand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id")
	public AreaT getRoom() {
		return this.room;
	}

	public void setRoom(AreaT room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_type_id", nullable = false)
	public StorageType getStorageType() {
		return this.storageType;
	}

	public void setStorageType(StorageType storageType) {
		this.storageType = storageType;
	}

	@Column(name = "equipment_number", length = 50)
	public String getEquipmentNumber() {
		return this.equipmentNumber;
	}

	public void setEquipmentNumber(String equipmentNumber) {
		this.equipmentNumber = equipmentNumber;
	}

	@Column(name = "name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "admin_name")
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "admin_detail")
	public String getAdminDetail() {
		return this.adminDetail;
	}

	public void setAdminDetail(String adminDetail) {
		this.adminDetail = adminDetail;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by")
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storage")
	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

}
