package dede.srm.models;
// Generated Feb 17, 2021, 3:01:45 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemType generated by hbm2java
 */
@Entity
@Table(name = "system_type", schema = "public")
public class SystemType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2073719686475578525L;
	private Long id;
	private String name;
	private Date createDate;
	private Date updateDate;
	private String createBy;
	private String updateBy;
	private String remark;
	private Set<java.lang.System> systems = new HashSet<java.lang.System>(0);

	public SystemType() {
	}

	public SystemType(Long id, String name, Date updateDate, String createBy, String updateBy, String remark) {
		this.id = id;
		this.name = name;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.remark = remark;
	}

	public SystemType(Long id, String name, Date createDate, Date updateDate, String createBy, String updateBy,
			String remark, Set<java.lang.System> systems) {
		this.id = id;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.remark = remark;
		this.systems = systems;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 22)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "create_by", nullable = false)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by", nullable = false)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "remark", nullable = false)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemType")
	public Set<java.lang.System> getSystems() {
		return this.systems;
	}

	public void setSystems(Set<java.lang.System> systems) {
		this.systems = systems;
	}

}
