package dede.srm.models;
// Generated Apr 16, 2021, 3:56:35 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * System generated by hbm2java
 */
@Entity
@Table(name = "system", schema = "public")
public class System implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6455811888056032560L;
	private Long id;
	private Device device;
	private SystemType systemType;
	private String name;
	private String os;
	private Integer cpuCoreUsage;
	private Float ramCapUsage;
	private Float diskUsage;
	private String kvm;
	private Date createDate;
	private Date updateDate;
	private String remark;
	private String username;
	private String password;
	private Long createBy;
	private Long updateBy;
	private String osVersion;
	private String otherDetail;
	private Long pdBrandId;
	private String systemPath;
	private List<IpAddress> ipAddresses;
	

	public System() {
	}

	public System(Long id, Device device, SystemType systemType, String name, String os, Date createDate,
			Date updateDate, String osVersion) {
		this.id = id;
		this.device = device;
		this.systemType = systemType;
		this.name = name;
		this.os = os;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.osVersion = osVersion;
	}

	public System(Long id, Device device, SystemType systemType, String name, String os, Integer cpuCoreUsage,
			Float ramCapUsage, Float diskUsage, String kvm, Date createDate, Date updateDate, String remark,
			String username, String password, Long createBy, Long updateBy, String osVersion, String otherDetail,
			Long pdBrandId, String systemPath) {
		this.id = id;
		this.device = device;
		this.systemType = systemType;
		this.name = name;
		this.os = os;
		this.cpuCoreUsage = cpuCoreUsage;
		this.ramCapUsage = ramCapUsage;
		this.diskUsage = diskUsage;
		this.kvm = kvm;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.remark = remark;
		this.username = username;
		this.password = password;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.osVersion = osVersion;
		this.otherDetail = otherDetail;
		this.pdBrandId = pdBrandId;
		this.systemPath = systemPath;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "system_type_id", nullable = false)
	public SystemType getSystemType() {
		return this.systemType;
	}

	public void setSystemType(SystemType systemType) {
		this.systemType = systemType;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "os", nullable = false)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "cpu_core_usage")
	public Integer getCpuCoreUsage() {
		return this.cpuCoreUsage;
	}

	public void setCpuCoreUsage(Integer cpuCoreUsage) {
		this.cpuCoreUsage = cpuCoreUsage;
	}

	@Column(name = "ram_cap_usage", precision = 8, scale = 8)
	public Float getRamCapUsage() {
		return this.ramCapUsage;
	}

	public void setRamCapUsage(Float ramCapUsage) {
		this.ramCapUsage = ramCapUsage;
	}

	@Column(name = "disk_usage", precision = 8, scale = 8)
	public Float getDiskUsage() {
		return this.diskUsage;
	}

	public void setDiskUsage(Float diskUsage) {
		this.diskUsage = diskUsage;
	}

	@Column(name = "kvm")
	public String getKvm() {
		return this.kvm;
	}

	public void setKvm(String kvm) {
		this.kvm = kvm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 22)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by")
	public Long getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "os_version", nullable = false)
	public String getOsVersion() {
		return this.osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	@Column(name = "other_detail")
	public String getOtherDetail() {
		return this.otherDetail;
	}

	public void setOtherDetail(String otherDetail) {
		this.otherDetail = otherDetail;
	}

	@Column(name = "pd_brand_id")
	public Long getPdBrandId() {
		return this.pdBrandId;
	}

	public void setPdBrandId(Long pdBrandId) {
		this.pdBrandId = pdBrandId;
	}

	@Column(name = "system_path", length = 200)
	public String getSystemPath() {
		return this.systemPath;
	}

	public void setSystemPath(String systemPath) {
		this.systemPath = systemPath;
	}
	
	@Transient
	public List<IpAddress> getIpAddresses() {
		return ipAddresses;
	}

	public void setIpAddresses(List<IpAddress> ipAddresses) {
		this.ipAddresses = ipAddresses;
	}
	

}
