package dede.srm.models;
// Generated Jan 21, 2021, 1:15:01 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Token generated by hbm2java
 */
@Entity
@Table(name = "user_token", schema = "public")
public class UserToken implements java.io.Serializable {

	private static final long serialVersionUID = -21634049446703644L;
	private Long id;
	private User user;
	private String jwtHash;
	private Date createDate;
	private String remark;
	private Date expireDate;

	public UserToken() {
	}

	public UserToken(Long id, User user, String jwtHash, Date createDate, Date expireDate) {
		this.id = id;
		this.user = user;
		this.jwtHash = jwtHash;
		this.createDate = createDate;
		this.expireDate = expireDate;
	}

	public UserToken(Long id, User user, String jwtHash, Date createDate, String remark, Date expireDate) {
		this.id = id;
		this.user = user;
		this.jwtHash = jwtHash;
		this.createDate = createDate;
		this.remark = remark;
		this.expireDate = expireDate;
	}

	@Id
	@SequenceGenerator(name = "token_id_seq", sequenceName = "token_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "token_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "jwt_hash", nullable = false)
	public String getJwtHash() {
		return this.jwtHash;
	}

	public void setJwtHash(String jwtHash) {
		this.jwtHash = jwtHash;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 22)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_date", nullable = false, length = 22)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

}
